name: Deploy to Staging

on:
  push:
    branches: [main]

jobs:
  deploy-staging:
    name: Deploy staging
    uses: AplinkosMinisterija/reusable-workflows/.github/workflows/biip-deploy.yml@main
    secrets: inherit
    permissions:
      contents: read
      packages: write
    with:
      environment: Staging
      enable-sentry: true
      docker-image: ghcr.io/AplinkosMinisterija/biip-uetk-api
      cache-from: type=registry,ref=ghcr.io/aplinkosministerija/biip-uetk-api:buildcache
      cache-to: type=registry,ref=ghcr.io/aplinkosministerija/biip-uetk-api:buildcache,mode=max,image-manifest=true,oci-mediatypes=true,ignore-error=true
