name: Deploy to Development

on:
  workflow_dispatch:

jobs:
  deploy-development:
    name: Deploy development
    uses: AplinkosMinisterija/reusable-workflows/.github/workflows/biip-deploy.yml@main
    secrets: inherit
    permissions:
      contents: read
      packages: write
    with:
      environment: Development
      enable-sentry: true
      docker-image: ghcr.io/AplinkosMinisterija/biip-uetk-api
      cache-from: type=registry,ref=ghcr.io/aplinkosministerija/biip-uetk-api:buildcache
      cache-to: type=registry,ref=ghcr.io/aplinkosministerija/biip-uetk-api:buildcache,mode=max,image-manifest=true,oci-mediatypes=true,ignore-error=true
